export const GET_TODOS_REQUEST = "GET_TODOS_REQUEST";
export const GET_TODOS_SUCCESS = "GET_TODOS_SUCCESS";
export const GET_TODOS_FAILURE = "GET_TODOS_FAILURE";

export const POST_TODO_REQUEST = "POST_TODO_REQUEST";
export const POST_TODO_SUCCESS = "POST_TODO_SUCCESS";
export const POST_TODO_FAILURE = "POST_TODO_FAILURE";

export const UPDATE_TODO_REQUEST ="UPDATE_TODO_REQUEST";
export const UPDATE_TODO_SUCCESS ="UPDATE_TODO_SUCCESS";
export const UPDATE_TODO_FAILURE ="UPDATE_TODO_FAILURE";
